### ISSUE TITLE
2 taps of back button or popup to exit app

### ISSUE THREAD

**Issue by jordan1776** [liftoff-app/liftoff#49] opened 2023-06-24 20:03 UTC
### Is your feature request related to a problem? Please describe.

It is easy to accidentally exit the app, if 6ou hit the back button too many times

### Describe the solution you'd like

Some apps when pressing the back button on the home menu give a toast saying pressing back again would exit the app.

### Describe alternatives you've considered

A yes/no popup would also work (with pressing back again just exiting the popup).

### Additional context

![Screenshot_20230624-160316](https://github.com/liftoff-app/liftoff/assets/6100101/be68c507-a490-43a9-81d9-c8fa08a6c07a)
![Screenshot_20230624-160254](https://github.com/liftoff-app/liftoff/assets/6100101/84399e75-efb9-4363-b287-ef51bd84c017)

**Comment by jordan1776** [comment] 2023-06-24 20:24
I realize this is a dupe of #24

**Comment by zachatrocity** [comment] 2023-06-24 20:45
Closing as dupe of #24

**Closed by zachatrocity** 2023-06-24 20:45 UTC
Labels: enhancement
