### ISSUE TITLE
Instance not working

### ISSUE THREAD

**Issue by SinTan1729** [liftoff-app/liftoff#156] opened 2023-06-29 09:11 UTC
### Device info

- OS: Android
- OS version: 13
- Device: Samsung Galaxy S22
- Liftoff version: 0.9.18

### The instance at [lemmy.sdf.org](lemmy.sdf.org) is not working.

When I try to add the instance, it says "Instance not found".

### Steps to reproduce

1. Go to Settings
2. Open Accounts
3. Click the menu in the bottom right
4. Click on "Add instance"
5. Type `lemmy.sdf.org` or `https://lemmy.sdf.org` in the given box.
6. It says "Instance not found".

### Relevant logs

<details>
  <summary>Logs</summary>
  
  Logs were empty.
</details>

### Expected behavior

The instance should be added.

**Comment by Maarten-buelens** [comment] 2023-06-29 13:59
I just tested it and it seems to be a problem only for 0.18.1-rc.1. 0.18 does seem to work.
Other instances like feddit.nl aldo dont work with the beta version.

**Comment by zachatrocity** [comment] 2023-06-29 14:04
This is fixed in the latest release build by @swmarks 

https://github.com/liftoff-app/liftoff/actions/runs/5413095145

**Comment by Maarten-buelens** [comment] 2023-06-29 15:18
Just tested a couple instances and 
0.18.1-rc.1 still aren't found.

**Comment by swmarks** [comment] 2023-06-29 19:00
I'm able to add this instance on my personal build that I made last night, looking into why it isn't happening on official release.

**Comment by swmarks** [comment] 2023-06-29 19:53
I think the issue is we didn't get the latest lemmy_api_client synced into Liftoff before the latest release:
https://github.com/liftoff-app/liftoff/commit/e1d9bffee38feca1559581833609ad151e4429be

I didn't know this had to be manually done, but I think it ought to work on the next release and I'll make sure this gets done after any future api changes. Sorry about that @SinTan1729 , @frap129 , and anyone else affected, I'm still learning 😬 

Thanks @zachatrocity for already fixing it! 🤘

**Comment by zachatrocity** [comment] 2023-06-29 20:05
No worries @swmarks, it should work better than this. I'll get the ci/CD set up next week

**Comment by zachatrocity** [comment] 2023-07-01 13:22
Fixed in 0.10.3

**Closed by zachatrocity** 2023-07-01 13:22 UTC
Labels: bug

**Comment by frap129** [comment] 2023-07-01 13:25
Works for me! Thanks!
