### ISSUE TITLE
Cannot add most instances blocked by lemmy.ml 

### ISSUE THREAD

**Issue by chersys** [liftoff-app/liftoff#212] opened 2023-07-02 06:47 UTC
### Device info

- OS: Android 
- OS version: 13
- Device: Pixel 7
- Liftoff version: 0.10.3

### Describe the bug

I can't add most instances blocked by lemmy.ml. It looks like LemmyApiV3 is blocking certain instances. 

I suspect that this is causing it: [https://github.com/LemmurOrg/lemmy_api_client/blob/master/lib/src/v3/models/api.freezed.dart](https://github.com/LemmurOrg/lemmy_api_client/blob/master/lib/src/v3/models/api.freezed.dart)

### Steps to reproduce

1. Go to Settings > Accounts > Add account > Add instance
2. Enter some instances blocked by lemmy.ml
3. It shows "instance not found"

### Expected behavior

New instance should be added

**Comment by swmarks** [comment] 2023-07-02 08:11
I've already figured out one issue for this. I'm going to go through that whole blocked list and make sure they resolve correctly.

**Comment by swmarks** [comment] 2023-07-02 08:44
Okay, so most of that list is either offline or not a Lemmy server, so that is one thing. If any of the servers that you were looking at are Lemmy v0.16, I doubt we're going to plan to support them because the API is significantly different. I also can't guarantee you that we'll fix bugs for versions less than v0.17.4 right now if there are any. It will probably depend on how much time it would take.

**Comment by chersys** [comment] 2023-07-02 10:02
I didn't notice that most of them are not lemmy instances. Thanks for pointing that out. These three instances running versions above 0.17.4 are getting blocked for no apparent reason. All of them are online. 

lemmy.services.coupou.fr - 0.17.4
exploding-heads.com - 0.18.0
lemmy.k6qw.com - 0.17.4

**Comment by inverimus** [comment] 2023-07-02 11:56
lemm.ee also does not work and is not blocked by lemmy.ml

**Comment by ChristinWhite** [comment] 2023-07-02 18:13
Is this possibly why vlemmy.net isn't found?

**Comment by swmarks** [comment] 2023-07-02 21:20
I can confirm that all of the specifically listed instances will be addable when we get the linked PR merged

**Closed** 2023-07-02 21:22 UTC
Labels: bug
