### ISSUE TITLE
Instance links opens email app on Android

### ISSUE THREAD

**Issue by soderluk** [liftoff-app/liftoff#134] opened 2023-06-28 12:31 UTC
### Device info

- OS: Android
- OS version: 13
- Device: OnePlus 8T
- Liftoff version: 0.9.18

### Describe the bug

When a post or comment includes a link to a community in the format `!<community>@<instance>`, and I tap the link, my phone opens up my email client. Does the app create a mailto:-link because of the @-sign?

### Steps to reproduce

1. Go to `!meta@sopuli.xyz`
2. Click on the sticky post: `"Welcome! Tervetuloa!"`
3. Scroll down to e.g. `@RegEx's` post about the black metal community, which links to `!black_metal@sopuli.xyz`
4. The phone's email app opens up, and sets the recipient to `black_metal@sopuli.xyz`

### Expected behavior

I would expect the LiftOff! app to open in the correct community when tapping on a community link within the app.

### Additional context

A note here, that sometimes the exclamation point is not included in the blue link. Might be user error as well, but thought it could be good to take a look at if it's not.

**Comment by zachatrocity** [comment] 2023-06-28 12:53
duplicate of #107

**Closed by zachatrocity** 2023-06-28 12:53 UTC
Labels: bug
