### ISSUE TITLE
Choppy scrolling in post with lots of comments

### ISSUE THREAD

**Issue by excitare** [liftoff-app/liftoff#154] opened 2023-06-29 08:59 UTC
### Device info

- OS: Android 
- OS version: 13
- Device: OnePlus 8T
- Liftoff version: 0.9.18

### Describe the bug

The scroll performance is very choppy for a post with a lot of comments.
Here's an example: https://lemmy.world/post/693680
This post has over 600 comments.

### Steps to reproduce

1. Go to the post (or a similar one with as many comments)
2. Let the comments load
3. Scroll down
4. Observe the scrolling behavior, it goes down to maybe 10 FPS.

### Expected behavior

Smooth scrolling.

### Additional context

The performance seems to degrade somewhat linearly. A post with 300 comments felt roughly half as bad.

**Comment by jordan1776** [comment] 2023-06-29 12:50
Dupe of #51 and being worked on

**Closed** 2023-06-29 13:08 UTC
Labels: bug
