### ISSUE TITLE
Searching for a specific community doesn't return any results

### ISSUE THREAD

**Issue by soderluk** [liftoff-app/liftoff#143] opened 2023-06-28 19:10 UTC
### Device info

- OS: Android
- OS version: 13
- Device: OnePlus 8T
- Liftoff version: 0.9.18

### Describe the bug

When searching for a community on another instance, I get no sensible results. On web the same search works, and returns the correct community.

### Steps to reproduce

1. Go to search
2. Choose your home instance, my case sopuli.xyz (I assume this is the same as Local on web), search for `!plugins@sh.itjust.works`
3. Go to the Communities tab, and observe no results.
4. Open the web search at https://sopuli.xyz/search, choose Local, and search for `!plugins@sh.itjust.works`
5. See one search result, which is `Lemmy Plugins & Userscripts@sh.itjust.works (https://sopuli.xyz/c/plugins@sh.itjust.works) - 6 subscribers`

### Expected behavior

I would expect the search results for the communities in the app to return at least the same results as the web search.

**Comment by TurnItOff-OnAgain** [comment] 2023-06-28 21:57
Search for the community name only, don't include the instance. I was able to find it by searching only for plugins

![Screenshot_20230628_175632](https://github.com/liftoff-app/liftoff/assets/26926284/8110f604-fd85-47c6-b95e-331f3b201e02)

**Comment by zachatrocity** [comment] 2023-06-28 22:29
Closing as this is working as intended. Trying to reduce the barrier of entry for community discovery. No sense in requiring the user to type the instance name in.

We have been considering a separate enhancement for a community discovery feature which would allow you to search and find communities outside of your instance that might come after our 1.0 release

**Closed by zachatrocity** 2023-06-28 22:29 UTC
Labels: bug

**Comment by soderluk** [comment] 2023-06-29 07:31
Well, now I feel just like an idiot 😅 I didn't even think of trying that version of searching. It's just that everywhere else the search requires the instance name, so I just assumed. Thanks for clarifying, and sorry for the inconvenience in creating unnecessary issues!

**Comment by zachatrocity** [comment] 2023-06-29 07:34
Not at all, we're all learning how lemmy works. Search is one way one place and a different in another. Its helpful for us to understand what people expect!
