### ISSUE TITLE
Comment collapsing should not be a long tap

### ISSUE THREAD

**Issue by CTalvio** [liftoff-app/liftoff#44] opened 2023-06-24 15:39 UTC
If anything, long tap should open the threedot context menu

Single tap currently does nothing, might as well make it collapse comments. Right now, the long tap to collapse slows down comment browsing in a very annoying manner.

**Comment by zachatrocity** [comment] 2023-06-24 19:25
Closing as duplicate of #30

**Closed by zachatrocity** 2023-06-24 19:25 UTC
Labels: enhancement
